version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: scheduler-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_scheduler

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:

    build: ./backend

    container_name: scheduler-backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      - mysql

  frontend:

    build: ./frontend

    container_name: scheduler-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:

  mysql_data: