"""add cron expression

Revision ID: 79397b45ddfd
Revises: 36d4c546ad5d
Create Date: 2026-07-05 14:23:49.635159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79397b45ddfd'
down_revision: Union[str, Sequence[str], None] = '36d4c546ad5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('cron_expression', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'cron_expression')
    # ### end Alembic commands ###
